### ISSUE TITLE
option --dyncomp-print-inc causes seg fault

### ISSUE THREAD

**Issue by GoogleCodeExporter** [codespecs/fjalar#10]
```
(don't remember if any time the options is used or certains test case(s))
seems to be around line 222 in kvasir_main.c.  I have a note that says when I 
fixed that is then got an assert in decls-output.c (around 484)
```

Original issue reported on code.google.com by `mar...@cs.washington.edu` on 5 Aug 2013 at 10:52

**Comment by markro49** [comment]
was able to repro in kvasir-tests/small-test with

 /homes/gws/markro/invariants/daikon7/scripts/kvasir-dtrace  --decls-only --with-dyncomp --decls-file=daikon-output/small-test.dyncomp.decls --dyncomp-print-inc ./small-test

**Comment by markro49** [comment]
must have a dtrace file specified to use --dyncomp-print-inc and --decls-only says no dtrace.  added a test and fatal error. running regressions now.

**Comment by markro49** [comment]
fixed
