### ISSUE TITLE
Kvasir-dtrace: Support for tracking external function calls

### ISSUE THREAD

**Issue by stan6** [codespecs/fjalar#14]
I have successfully ran the wordplay.c example in daikon to produce a trace using kvasir-dtrace. I realized that external function calls like strlen() are not included in the .dtrace file. Is the support for external function calls available for the kvasir front end for C program?

**Comment by markro49** [comment]
Not exactly sure what you mean by an 'external function'.  Your example, 'strlen' is a member of the standard C/C++ runtime and its internal values are not usually considered interesting. The .dtrace file only contains information about variables declared in the user program.  Calls into functions contained in an external library are tracked at the assembly code level as they may cause user variables to become related - but the variables declared in those external functions are not displayed.  They are usually of no interest and in most cases there is no source available for them and they  probably were not compiled -gdwarf-2 as well.  Finally, it should be noted that some standard library routines (such as strlen or memcpy) are often converted to inline code by the compiler further making such tacking almost impossible.

**Comment by stan6** [comment]
Thanks for the quick response. The example I provide is indeed not a good one. 

I have program with similar structure as following example. My problem is that the external function  like "WriteMyString()" is not included as program point in the .dtrace file so I thought it is because this functionality is not supported. However, my concern is invalidated because the simple example below actually include "WriteMyString()" as in the .dtrace file. 

I think I may be using the incorrect option for compilation. I am using "./configure CFLAGS=-gdwarf-2 -O0 -fno-inline" for configuring the compiler option. Is this option sufficient?

/*
 *	header.h
 */
#define MY_STRING "Hello World"

void WriteMyString();


/*
 *	WriteMyString.c
 */
extern char	*AnotherString;

void WriteMyString(ThisString)
char	*ThisString;
{
	printf("%s\n", ThisString);
	printf("Global Variable = %s\n", AnotherString);
}

/*
 *      main.c
 */
#include "header.h"
#include <stdio.h>

char    *AnotherString = "Hello Everyone";

main()
{
        printf("Running...\n");

        /*
         *      Call WriteMyString() - defined in another file
         */
        WriteMyString(MY_STRING);

        printf("Finished.\n");
}

**Comment by markro49** [comment]
I am confused by your comment.  First you say "WriteMyString" is not included in the .dtrace file and then you say it is.  What exactly is your question?

Your compilation options look fine.

**Comment by stan6** [comment]
Thanks for the response. I am sorry I could not produce a minimal example to show why the external function is not included in the .dtrace file.

I think that the problem I mentioned is program-specific. Hence, I am closing this issue.
