### ISSUE TITLE
Porting Kvasir to ARM

### ISSUE THREAD

**Issue by Ricoblack** [codespecs/fjalar#19]
Has anyone tried to use Kvasir on ARM? If not, do you think is it possible or is too much difficult?
In particular ARM/Linux and ARM/Android.

**Comment by markro49** [comment]
While it could be done, I think it would be quite a bit of work.  First the good news - Fjalar is built on top of the Valgrind system and that supports ARM.  The bad news is there is a lot of code in fjalar_main.c, fjalar_runtime.c, kvasir/dyncomp_translate.c and kvasir/dyncomp_runtime.c that ignores the possibility of other machine architectures and just assumes X86 (or AMD64 to be more specific).  We only deal with X86 registers in the GuestState and machine State data structures, for example.  If you wish to pursue this we would provide what support we could, but it is not a feature we are interested in implementing ourselves.

We support only Linux and Linux look alikes (Cygwin64, MACOSX) - I have no idea what would be involved in running on Android.

Thank you
