### ISSUE TITLE
Can't comile with basic-tool.c

### ISSUE THREAD

**Issue by danielaldam** [codespecs/fjalar#20]
Fjalar version 5.4.5
I ran auto-everything.sh in order to compile fjalar, which worked.
then i added basic-tool/basic-tool.c to makefile.am, as instructed in the programmer's manual.
I ran auto-everything.sh again but now got the following error:
```
basic-tool/../dwarf.h:232:34: error: unknown type name ‘size_t’
extern void * xcrealloc (void *, size_t, size_t);
```
I tried adding
`#include  <stdio.h>`
to dwarf.h, since it contains the defenition for size_t, but then got the following error:
```
/usr/include/stdio.h:48:25: error: conflicting types for ‘FILE’
typedef struct _IO_FILE FILE;
```

**Comment by mernst** [comment]
I'm sorry you are having trouble.  We would like to help you, but your bug report does not enable us to do so.

Can you please provide the information requested in the [Reporting problems](https://plse.cs.washington.edu/daikon/download/doc/daikon.html#Reporting-problems) section of the manual?

The manual instructs you to provide us exact input (don't just describe what you did in words), compilete output (don't just show a snippet), and indicate your operating system and compiler, among other things.

Thanks!

**Comment by danielaldam** [comment]
i uploaded the changed Makefile.am, though i added .txt to the extension, since git does not allow uploading .am files. the change is in line 77
[Makefile.am.txt](https://github.com/codespecs/fjalar/files/674529/Makefile.am.txt)

basic-tool.c, is the example tool provided in the prooject, unchanged

i ran auto-everything.sh the following way:
`sh auto-everything.sh 2> errors.txt 1> output.txt`
(errors.txt and output.txt are attached)

[errors.txt](https://github.com/codespecs/fjalar/files/674526/errors.txt)
[output.txt](https://github.com/codespecs/fjalar/files/674527/output.txt)

I'm using Ubuntu 14.04.5 LTS (kernel version: 4.4.0-53-generic)

**Comment by markro49** [comment]
There were a couple of problems here: both the source for the sample test was incorrect and the instructions for how to build the sample tool was slightly off.  See the most recent commits:
e1c9fa8
6fa130c
