### ISSUE TITLE
crash after assertion in generate_fjalar_entries.c initMemberFuncs() line 3185

### ISSUE THREAD

**Issue by xor2003** [codespecs/fjalar#21]
Centos 6 x86_64
gcc версия 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
daikon-5.5.8.zip (2 June 2017, 97 Mbytes)
crash after assertion:
[crash_generate_fjalar_entries.c_initMemberFuncs_3185.zip](https://github.com/codespecs/fjalar/files/1049228/crash_generate_fjalar_entries.c_initMemberFuncs_3185.zip)

**Comment by markro49** [comment]
I'm sorry you're having a problem with Fjalar - but I cannot help with without more information.  I need the binary you tried to process and the exact set of steps you used to build and run fjalar.

Thank you,
Mark Roberts

**Comment by markro49** [comment]
Closing - no response from original reporter.
