### ISSUE TITLE
Issue when running Kvasir

### ISSUE THREAD

**Issue by satbekmyrza** [codespecs/fjalar#48]
Hello, 
I am trying to run Kvasir on our university server through SSH. How do I fix the error? Your help is much appreciated.

**The following are the steps I went through:**
_Step 1. Download and unpack Daikon_
```
cd daikonparent
wget http://plse.cs.washington.edu/daikon/download/daikon-5.8.6.tar.gz
tar zxf daikon-5.8.6.tar.gz
```

_Step 2. Modify .bashrc_
```
#The absolute pathname of the directory that contains Daikon
export DAIKONDIR=daikonparent/daikon-5.8.6
source $DAIKONDIR/scripts/daikon.bashrc
```

_Step 3. Get Fjalar_
```
cd $DAIKONDIR
cd ..
git clone https://github.com/codespecs/fjalar.git
```

_Step 4. Make Kvasir_
```
cd $DAIKONDIR
make kvasir
```

_Step 5. Start using Kvasir_
```
cd $DAIKONDIR/scripts/
gcc -g -no-pie total.c
kvasir-dtrace ./a.out
```

**The error I get after `kvasir-dtrace ./a.out` is the following:**
```
==16605== kvasir-5.8.6, C/C++ Language Front-End for Daikon with DynComp comparability analysis tool.
==16605== Copyright (C) 2007-2020, University of Washington CSE PLSE Group
==16605== Using Valgrind-3.16.1.Fjalar and LibVEX; rerun with -h for copyright info
==16605== Command: ./a.out
==16605==

kvasir: generate_fjalar_entries.c:647 (repCheckAllEntries): Assertion 'f->endPC' failed.
Segmentation fault (core dumped)
```

**GCC version:**
```
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```

**total.c:**
```
#include <stdio.h>
#include <stdlib.h>
int main()
{
        int n = 10, i, total = 0;
        int *arr;
        arr = (int *) malloc(n * sizeof(int));
        for (i = 0; i < n; i++) {
                arr[i] = i * i;
                total += arr[i];
        }
        printf("Total = %d\n", total);
        free(arr);
        return 0;
}
```

**Comment by markro49** [comment]
Your gcc compiler options are incorrect.  From the Daikon User Manual, section 7.3:
"To use Kvasir, first compile your program using the DWARF-2 debugging format (e.g., supply the -gdwarf-2 option to gcc) and without optimizations (e.g., supply the -O0 option to gcc). Also, some versions of gcc now output position independent code by default. Kvasir cannot properly process these binaries. You must add the -no-pie option to disable this feature. "

So using -g is incorrect, you must use -gdwarf-2.

**Comment by satbekmyrza** [comment]
Thank you, Mark!
