### ISSUE TITLE
Unable to build Kvasir

### ISSUE THREAD

**Issue by sharkov63** [codespecs/fjalar#56]
Hello! I failed to build Kvasir on Microsoft WSL 2 (Ubuntu 22.04):
```sh
$ uname -a
Linux uWX1176834lnlp 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
My steps were:
1. I made a local clone of [Daikon repository](https://github.com/codespecs/daikon) into `~/daikonparent/daikon`.
2. I successfully built Daikon (master), according to the instructions.
3. I made a local clone of fjalar repository into `~/daikonparent/fjalar`.
4. I attempted to build kvasir:
```sh
$ cd ~/daikonparent/daikon
$ make kvasir
```
The output was [make-kvasir.zip](https://github.com/codespecs/fjalar/files/9071774/make-kvasir.zip).

I made some changes to the source code to make the build work, see #55 .

Please, take a look.

Thanks,
Danila

**Comment by markro49** [comment]
Could you please verify your Linux version with this command: 'lsb_release -a'
Thank you

**Comment by markro49** [comment]
I built a wsl Unbuntu 22.04 system and was able to reproduce your failure.  I will investigate further.

**Comment by sharkov63** [comment]
> Could you please verify your Linux version with this command: 'lsb_release -a' Thank you

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

**Comment by markro49** [comment]
This issue has been fixed with commit: https://github.com/codespecs/fjalar/commit/353ee0086ae0ee78b90e5be32ad00f697c09a22a
